CREATE TABLE ability (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    supertype TEXT,
    subtype TEXT,
    image_url TEXT,
    world TEXT NOT NULL,
    usage TEXT,
    range INTEGER,
    strength INTEGER,
    effects TEXT,
    utility TEXT,
    difficulty TEXT,
    talent TEXT,
    enablers TEXT,
    requirements TEXT,
    prevalence TEXT,
    system TEXT,
    construct TEXT
);