CREATE TABLE narrative (
    history TEXT,
    consequences TEXT,
    start_date INTEGER,
    end_date INTEGER,
    events TEXT,
    characters TEXT,
    objects TEXT,
    locations TEXT,
    species TEXT,
    creatures TEXT,
    institutions TEXT,
    traits TEXT,
    collectives TEXT,
    territories TEXT,
    abilities TEXT,
    phenomena TEXT,
    languages TEXT,
    families TEXT,
    relations TEXT,
    titles TEXT,
    constructs TEXT
);