CREATE TABLE object (
    aesthetics TEXT,
    weight INTEGER,
    amount INTEGER,
    parent_object TEXT,
    technology TEXT,
    utility TEXT,
    effects TEXT,
    enables TEXT,
    consumes TEXT,
    origins TEXT,
    location TEXT,
    craftsmanship TEXT,
    requirements TEXT,
    durability TEXT,
    value INTEGER,
    damage INTEGER,
    armor INTEGER,
    rarity TEXT,
    language TEXT,
    requires TEXT
);