CREATE TABLE phenomenon (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    supertype TEXT,
    subtype TEXT,
    image_url TEXT,
    world TEXT NOT NULL,
    presence TEXT,
    scope TEXT,
    duration INTEGER,
    intensity TEXT,
    empowerments TEXT,
    environments TEXT,
    carriers TEXT,
    effect TEXT,
    catalysts TEXT,
    wielders TEXT,
    handlers TEXT,
    enablers TEXT,
    triggers TEXT,
    affinity TEXT
);