CREATE TABLE relation (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    supertype TEXT,
    subtype TEXT,
    image_url TEXT,
    world TEXT NOT NULL,
    history TEXT,
    impact TEXT,
    start_date INTEGER,
    end_date INTEGER,
    debt INTEGER,
    events TEXT,
    primary_character TEXT,
    primary_creature TEXT,
    primary_institution TEXT,
    secondary_characters TEXT,
    secondary_creatures TEXT,
    secondary_institutions TEXT
);