CREATE TABLE territory (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    supertype TEXT,
    subtype TEXT,
    image_url TEXT,
    world TEXT NOT NULL,
    terrain TEXT,
    size INTEGER,
    parent_territory TEXT,
    maintenance TEXT,
    primary_output INTEGER,
    secondary_output INTEGER,
    primary_resource TEXT,
    secondary_resources TEXT,
    history TEXT,
    occupants TEXT,
    occurrences TEXT
);