name: YAML to JSON Conversion

on:
  push:
    paths:
      - 'schema/**/*.yaml'  # Trigger the workflow when a YAML file in the schema directory is pushed

jobs:
  convert:
    runs-on: ubuntu-latest  # Running the job on the latest version of Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Sets up Python version 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml  # Install PyYAML to work with YAML files

      - name: Convert YAML to JSON
        run: |
          python ./scripts/yaml_to_json.py
        working-directory: ${{ github.workspace }}  # Sets the working directory to the root of your repository

