name: YAML to Obsidian Templates Conversion

on:
  push:
    paths:
      - 'schema/**/*.yaml'  # Trigger the workflow when a YAML file in the schema directory is pushed

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensures the workflow has permission to commit and push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Fetch latest changes from main
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Convert YAML to Templates
        run: python ./scripts/yaml_to_obsidian_templates.py

      # Auto-commit changes
      - name: Add changes
        run: git add .

      - name: Commit and Push Templates files
        run: |
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update Templates files from YAML"
            git push origin HEAD:main
          fi

      - name: Complete job
        run: echo "Conversion and update complete!"
