name: YAML to JSON Conversion

on:
  push:
    paths:
      - 'schema/**/*.yaml'  # Trigger the workflow when a YAML file in the schema directory is pushed

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install pyyaml

      - name: Convert YAML to JSON
        run: python ./scripts/yaml_to_json.py

      - name: Commit JSON files 
        run: | 
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add languages/json/*.json
          git commit -m "Auto-update JSON files from YAML" || echo "No changes to commit"
          git push https://${{ secrets.ACTIONS_TOKEN }}@github.com/OnlyWorlds/OnlyWorlds.git

      - name: Complete job
        run: echo "Conversion and update complete!"
