name: Trigger Documentation Update

on:
  push:
    paths:
      - 'schema/**/*.yaml'

jobs:
  trigger-update:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_ACCESS }}
          repository: onlyworlds/onlyworlds.github.io
          event-type: update-docs
